org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
systemProp.java.net.preferIPv4Stack=true

mod_version=0.5.1
minecraft_version=1.21.1
minecraft_range=[1.21.1,1.21.2)
neo_version=21.1.241
neo_range=[21.1.0,21.2.0)
loader_range=[4,)
parchment_minecraft_version=1.21.1
parchment_version=2024.11.17

tconstruct_version=3.12.5
tconstruct_range=[3.12.5,)
mantle_version=1.12.4
