modLoader="javafml"
loaderVersion="${loader_range}"
license="MIT"

[[mods]]
modId="tinkerleveling"
version="${version}"
displayName="Tinker Leveling"
authors="embeddedt"
description='''
A rewrite of Tinkers Tool Leveling for modern Minecraft versions.
'''

[[dependencies.tinkerleveling]]
modId="neoforge"
type="required"
versionRange="${neo_range}"
ordering="NONE"
side="BOTH"

[[dependencies.tinkerleveling]]
modId="minecraft"
type="required"
versionRange="${minecraft_range}"
ordering="NONE"
side="BOTH"

[[dependencies.tinkerleveling]]
modId="tconstruct"
type="required"
versionRange="${tconstruct_range}"
ordering="AFTER"
side="BOTH"

